INSERT INTO region(name) VALUES ('Occitanie');
INSERT INTO region(name) VALUES ('Bretagne');
INSERT INTO region(name) VALUES ('Pays de la Loire');
INSERT INTO region(name) VALUES ('Île-de-France');
INSERT INTO region(name) VALUES ('Corse');
INSERT INTO region(name) VALUES ('Provence-Alpes-Côte-D''Azur');
INSERT INTO region(name) VALUES ('Auvergne-Rhône-Alpes');
INSERT INTO region(name) VALUES ('Bourgogne-Franche-Comté');
INSERT INTO region(name) VALUES ('Hauts-de-France');
INSERT INTO region(name) VALUES ('Grand Est');
INSERT INTO region(name) VALUES ('Nouvelle Aquitaine');
INSERT INTO region(name) VALUES ('Normandie');
INSERT INTO region(name) VALUES ('Centre Val De Loire');